export interface SearchItem {
  id: string;
  title: string;
  titleEn: string;
  description: string;
  descriptionEn: string;
  keywords: string;
  keywordsEn: string;
  href: string;
}

export const searchData: SearchItem[] = [
  {
    id: "home",
    title: "首页",
    titleEn: "Home",
    description: "一个农民、一个方程、一场可能改变人类文明的实验。张祥前统一场论信息站。",
    descriptionEn: "A farmer, an equation, an experiment that could change civilization. Zhang Xiangqian's unified field theory.",
    keywords: "统一场论 张祥前 变化电磁场 引力场 人工场",
    keywordsEn: "unified field theory Zhang Xiangqian electromagnetic gravitational artificial field",
    href: "/",
  },
  {
    id: "theory-overview",
    title: "理论总览",
    titleEn: "Theory Overview",
    description: "宇宙只有物体和空间两种存在，四种基本力是空间螺旋运动的不同分量。果克动量公式 P=m(C-v)。",
    descriptionEn: "Only matter and space exist. Four forces are components of helical motion. Guoke momentum P=m(C-v).",
    keywords: "统一场论 四力统一 螺旋运动 果克动量 电场 磁场 引力场 核力",
    keywordsEn: "unified field theory four forces helical motion Guoke momentum electric magnetic gravitational nuclear",
    href: "/theory/overview",
  },
  {
    id: "theory-time",
    title: "时间的本质",
    titleEn: "The Nature of Time",
    description: "时间是观察者对周围空间光速发散运动的感受。时空同一化方程 R=Ct。张飞张翼德类比解释光速不变。",
    descriptionEn: "Time is the observer's perception of space diverging at light speed. R=Ct equation. Zhang Fei analogy for light speed constancy.",
    keywords: "时间 光速不变 时空同一化 R=Ct 张飞 张翼德",
    keywordsEn: "time speed of light spacetime unification R=Ct Zhang Fei analogy",
    href: "/theory/time",
  },
  {
    id: "theory-mass",
    title: "质量的本质",
    titleEn: "The Nature of Mass",
    description: "质量是空间位移的条数。质量归零则自动光速运动。飞碟三种时空状态：平常态、准激发态、激发态。",
    descriptionEn: "Mass equals spatial displacement lines. Zero mass means automatic light-speed motion. Three spacetime states of flying saucers.",
    keywords: "质量 空间位移 激发态 准激发态 飞碟 光速 零质量",
    keywordsEn: "mass spatial displacement excited state quasi-excited flying saucer light speed zero mass",
    href: "/theory/mass",
  },
  {
    id: "theory-field",
    title: "场的本质",
    titleEn: "The Nature of Fields",
    description: "场是空间的运动模式。螺旋运动三分量：直线速度=电场、环绕速度=磁场、向心加速度=引力场。",
    descriptionEn: "Fields are patterns of spatial motion. Helical components: linear=electric, rotational=magnetic, centripetal=gravitational.",
    keywords: "场 电场 磁场 引力场 核力场 螺旋运动 空间运动",
    keywordsEn: "field electric magnetic gravitational nuclear helical motion spatial motion",
    href: "/theory/field",
  },
  {
    id: "theory-equations",
    title: "核心公式集",
    titleEn: "Core Equations",
    description: "统一场论18个核心公式。万有统一方程 P=(C-V)M 对时间求导得四种力。大统一推导。",
    descriptionEn: "18 core equations. Universal unification P=(C-V)M differentiated yields four forces. Grand unification derivation.",
    keywords: "公式 方程 万有统一 磁场定义 时空统一 四力推导 大统一",
    keywordsEn: "equations formulas universal unification magnetic field spacetime four forces grand unification",
    href: "/theory/equations",
  },
  {
    id: "theory-unification",
    title: "时空归一化方程",
    titleEn: "Spacetime Unification Equation",
    description: "G、h、c在同一个方程中。开普勒定律+德布罗意关系=三大理论统一。施瓦西半径推论。",
    descriptionEn: "G, h, c in one equation. Kepler's law + de Broglie relation = unifying three theories. Schwarzschild radius corollary.",
    keywords: "归一化方程 开普勒 德布罗意 施瓦西半径 引力常数 普朗克常数 光速",
    keywordsEn: "unification equation Kepler de Broglie Schwarzschild radius gravitational constant Planck constant speed of light",
    href: "/theory/unification-equation",
  },
  {
    id: "theory-deepdive",
    title: "从零开始理解统一场论",
    titleEn: "Understanding UFT from Scratch",
    description: "11步阶梯式科普。不用公式，从零基础一步步构建完整理论图景。量子纠缠四大矛盾解释。",
    descriptionEn: "11-step explainer. No formulas needed, building the complete theoretical picture from scratch. Four QM-relativity contradictions resolved.",
    keywords: "科普 入门 零基础 量子纠缠 四大矛盾 电荷 质量 时间",
    keywordsEn: "explainer beginner introduction quantum entanglement contradictions charge mass time",
    href: "/theory/deep-dive",
  },
  {
    id: "theory-visualization",
    title: "交互式可视化",
    titleEn: "Interactive Visualization",
    description: "三个交互式Canvas动画：空间螺旋运动、四种力分解、量子纠缠空间结构解释。",
    descriptionEn: "Three interactive Canvas animations: spatial helical motion, four force decomposition, quantum entanglement spatial structure explanation.",
    keywords: "可视化 动画 螺旋运动 四种力 量子纠缠 Canvas",
    keywordsEn: "visualization animation helical motion four forces quantum entanglement Canvas",
    href: "/theory/visualization",
  },
  {
    id: "experiment-overview",
    title: "实验总览",
    titleEn: "Experiment Overview",
    description: "2023年首次发现变化电磁场产生引力场效应。加速电荷实验、旋转实验、质量变化实验、低压突破。",
    descriptionEn: "First discovery of changing EM fields producing gravitational effects in 2023. Charge acceleration, rotation, mass change experiments.",
    keywords: "实验 变化电磁场 引力场 加速电荷 旋转 质量变化 低压",
    keywordsEn: "experiment changing electromagnetic gravitational accelerating charge rotation mass change low voltage",
    href: "/experiment/overview",
  },
  {
    id: "experiment-setup",
    title: "实验方案",
    titleEn: "Experimental Setup",
    description: "可复现的实验方案。硅胶管高压方案、场发动机一号、真空罐方案、漆包线线圈方案、法拉第笼验证。",
    descriptionEn: "Reproducible experimental setups. Silicone tube, field engine, vacuum chamber, enameled wire coils, Faraday cage verification.",
    keywords: "实验方案 复现 硅胶管 高压包 真空罐 漆包线 法拉第笼 设备清单",
    keywordsEn: "experimental setup replication silicone tube high voltage vacuum chamber enameled wire Faraday cage equipment",
    href: "/experiment/setup",
  },
  {
    id: "experiment-videos",
    title: "实验视频",
    titleEn: "Experiment Videos",
    description: "张祥前实验演示视频。加速电荷引力场实验、变化磁场旋转实验、低压方案演示。",
    descriptionEn: "Zhang Xiangqian experiment demonstration videos. Charge acceleration, magnetic field rotation, low-voltage setup.",
    keywords: "视频 实验演示 B站",
    keywordsEn: "video experiment demonstration Bilibili",
    href: "/experiment/videos",
  },
  {
    id: "experiment-replicate",
    title: "呼吁复现",
    titleEn: "Call for Replication",
    description: "独立复现是最关键的一步。设备预算约2000-2500元。大学物理实验室即可尝试。",
    descriptionEn: "Independent replication is the most critical step. Equipment budget ~$300-500 USD. University physics labs can attempt it.",
    keywords: "复现 独立验证 实验室 设备预算 科学方法",
    keywordsEn: "replication independent verification laboratory equipment budget scientific method",
    href: "/experiment/replicate",
  },
  {
    id: "comparison-navy",
    title: "美国海军专利对比",
    titleEn: "US Navy Patent Comparison",
    description: "张祥前理论与Pais专利对比。US10144532B2惯性质量减少、US10322827引力波发生器、US12417870。",
    descriptionEn: "Zhang's theory vs Pais patents. US10144532B2 inertial mass reduction, US10322827 gravitational wave generator, US12417870.",
    keywords: "美国海军 Pais 专利 惯性质量减少 引力波 US10144532B2 US10322827 US12417870",
    keywordsEn: "US Navy Pais patent inertial mass reduction gravitational wave US10144532B2 US10322827 US12417870",
    href: "/comparison/navy-patents",
  },
  {
    id: "comparison-mainstream",
    title: "与主流物理学的关系",
    titleEn: "Relationship with Mainstream Physics",
    description: "向下兼容牛顿力学。自然推出相对论质速公式。法拉第电磁感应是完整方程的一半。量子现象解释。",
    descriptionEn: "Backward compatible with Newton. Derives relativistic mass-velocity. Faraday induction is half the equation. Quantum explanations.",
    keywords: "牛顿力学 相对论 法拉第 电磁感应 量子纠缠 双缝干涉",
    keywordsEn: "Newtonian mechanics relativity Faraday electromagnetic induction quantum entanglement double slit",
    href: "/comparison/mainstream",
  },
  {
    id: "applications",
    title: "人工场扫描十大应用",
    titleEn: "Top 10 Applications",
    description: "光速飞碟、全球运动网、汇聚太阳能、人工信息场医疗、意识永生、时空冰箱、虚拟建筑、冷焊技术。",
    descriptionEn: "Light-speed saucers, global transport, solar energy, medical field, consciousness immortality, spacetime fridge, virtual architecture.",
    keywords: "应用 飞碟 全球运动网 太阳能 医疗 永生 时空冰箱 虚拟建筑 冷焊",
    keywordsEn: "applications flying saucer transport solar energy medical immortality spacetime fridge virtual architecture cold welding",
    href: "/applications/overview",
  },
  {
    id: "guoke-overview",
    title: "果克文明概述",
    titleEn: "Guoke Civilization Overview",
    description: "果克星球高度发达外星文明。9个同步轨道人工场发射中心。无国家、算法协议联盟治理。",
    descriptionEn: "Guoke planet advanced alien civilization. 9 orbital field emission centers. No nations, algorithm protocol governance.",
    keywords: "果克星球 外星文明 人工场发射中心 算法治理 无国家",
    keywordsEn: "Guoke planet alien civilization field emission center algorithm governance no nations",
    href: "/guoke/overview",
  },
  {
    id: "guoke-evolution",
    title: "文明演变路径",
    titleEn: "Civilization Evolution",
    description: "果克文明8个阶段：原始社会、场本质破译、两大网络、国家消亡、算法联盟、个人自由、宗教消亡、数学家掌权。",
    descriptionEn: "8 stages: primitive society, field decoded, two networks, nations dissolve, algorithm alliance, individual freedom, religion ends, mathematicians rule.",
    keywords: "文明演变 八个阶段 国家消亡 算法联盟 数学家 宗教消亡",
    keywordsEn: "civilization evolution eight stages nations dissolve algorithm alliance mathematicians religion",
    href: "/guoke/evolution",
  },
  {
    id: "guoke-book",
    title: "果克星球奇遇记",
    titleEn: "Adventures on Planet Guoke",
    description: "张祥前的叙事作品。1985年外星旅行经历。关键人物：列文、苏代尔、微丽。",
    descriptionEn: "Zhang Xiangqian's narrative. 1985 alien journey. Key characters: Liewen, Sudaier, Weili.",
    keywords: "果克星球奇遇记 书籍 列文 苏代尔 微丽 1985",
    keywordsEn: "Adventures Planet Guoke book Liewen Sudaier Weili 1985",
    href: "/guoke/book",
  },
  {
    id: "about-zhang",
    title: "张祥前简介",
    titleEn: "About Zhang Xiangqian",
    description: "安徽庐江农民，自1985年起研究统一场论四十年。美国专利US12417870。",
    descriptionEn: "Farmer from Lujiang, Anhui. Researching unified field theory for 40 years since 1985. US patent US12417870.",
    keywords: "张祥前 安徽 庐江 农民 四十年 1985 专利",
    keywordsEn: "Zhang Xiangqian Anhui Lujiang farmer forty years 1985 patent",
    href: "/about/zhang",
  },
  {
    id: "resources",
    title: "资源与联系",
    titleEn: "Resources & Contact",
    description: "原始资料下载、独立复现呼吁、联系方式。Google Drive资料库。",
    descriptionEn: "Original materials download, call for independent replication, contact information. Google Drive repository.",
    keywords: "资源 下载 联系 复现 Google Drive 资料",
    keywordsEn: "resources download contact replication Google Drive materials",
    href: "/resources",
  },
  {
    id: "about-project",
    title: "关于本项目",
    titleEn: "About This Project",
    description: "本站建设初衷、信息来源说明、免责声明。不做真假判断，呼吁独立实验复现。",
    descriptionEn: "Site purpose, information sources, disclaimer. No truth claims, calling for independent experimental replication.",
    keywords: "关于 免责声明 信息来源 独立验证",
    keywordsEn: "about disclaimer information sources independent verification",
    href: "/about/project",
  },
];
