import type { Metadata } from "next";
import NextRead from "@/components/NextRead";
import type { Locale } from "@/lib/i18n";

export function generateMetadata({ params }: { params: { locale: string } }): Metadata {
  const isEn = params.locale === "en";
  return {
    title: isEn
      ? "About This Project — Unified Field Theory Information Site"
      : "关于本项目 — 统一场论信息站",
    description: isEn
      ? "The purpose of this site, information sources, and disclaimers. We make no truth claims and call for independent experimental replication."
      : "本站的建设初衷、信息来源说明和免责声明。我们不做真假判断，呼吁独立实验复现。",
  };
}

export default function ProjectPage({ params }: { params: { locale: string } }) {
  const loc = (params.locale === "en" ? "en" : "zh") as Locale;
  const isEn = loc === "en";
  const t = <T,>(zh: T, en: T): T => (isEn ? en : zh);

  return (
    <div className="max-w-4xl mx-auto px-4 py-12">
      <div className="prose">
        <h1>{t("关于本项目", "About This Project")}</h1>

        <h2>{t("这个网站是怎么来的", "How This Website Came to Be")}</h2>
        <p>
          {t(
            "我们注意到张祥前的统一场论和他的实验，也注意到美国海军在类似方向的专利。我们认为，这些信息值得被系统整理和呈现，让更多有科学素养的人了解和评判。",
            "We noticed Zhang Xiangqian's unified field theory and his experiments, as well as US Navy patents in a similar direction. We believe this information deserves to be systematically organized and presented, so that more scientifically literate people can learn about it and form their own judgments."
          )}
        </p>
        <p>
          {t(
            <>这个网站的目标很简单：<strong>把信息整理清楚，方便人们做出自己的判断</strong>。我们不是张祥前的代言人，也不是他的批评者。我们是信息的整理者。</>,
            <>The goal of this website is simple: <strong>organize the information clearly so people can make their own judgments</strong>. We are not Zhang Xiangqian&apos;s advocates, nor his critics. We are curators of information.</>
          )}
        </p>

        <h2>{t("信息来源", "Information Sources")}</h2>
        <p>
          {t(
            "本站所有内容基于以下公开资料整理：",
            "All content on this site is compiled from the following publicly available materials:"
          )}
        </p>
        <ul>
          <li>{t("张祥前著《统一场论》第七版", "Unified Field Theory (7th Edition) by Zhang Xiangqian")}</li>
          <li>{t("张祥前著《果克星球奇遇记》", "Adventures on Planet Guoke by Zhang Xiangqian")}</li>
          <li>{t("张祥前著《变化电磁场产生引力场试验及简化推导》", "Experiments and Simplified Derivation of Gravitational Fields Generated by Changing Electromagnetic Fields by Zhang Xiangqian")}</li>
          <li>{t("张祥前著《时间 空间 物质 信息 宇宙核心秘密》", "Time, Space, Matter, Information: Core Secrets of the Universe by Zhang Xiangqian")}</li>
          <li>{t("美国专利 US10144532B2（Pais，惯性质量减少装置）", "US Patent US10144532B2 (Pais, Inertial Mass Reduction Device)")}</li>
          <li>{t("美国专利 US10322827（Pais，引力波发生器）", "US Patent US10322827 (Pais, Gravity Wave Generator)")}</li>
          <li>{t("美国专利 US12417870（张祥前）", "US Patent US12417870 (Zhang Xiangqian)")}</li>
        </ul>

        <h2>{t("我们的立场", "Our Position")}</h2>
        <div className="bg-primary-50 p-6 rounded-lg my-6">
          <ul className="space-y-3">
            <li>
              {t(
                <><strong>我们不判断真假。</strong>张祥前的理论尚未经过学术同行评审，实验结果尚未经过独立第三方验证。我们如实呈现信息，不做正确性判断。</>,
                <><strong>We make no truth claims.</strong> Zhang Xiangqian&apos;s theories have not undergone academic peer review, and his experimental results have not been independently verified by third parties. We present the information as-is, without judging its correctness.</>
              )}
            </li>
            <li>
              {t(
                <><strong>我们呼吁实验验证。</strong>理论的价值最终要靠实验说话。我们呼吁有条件的实验室和研究者进行独立复现实验。</>,
                <><strong>We call for experimental verification.</strong> The value of a theory must ultimately be proven by experiments. We urge qualified laboratories and researchers to conduct independent replication experiments.</>
              )}
            </li>
            <li>
              {t(
                <><strong>我们尊重科学方法。</strong>即使理论来源非传统，只要它做出可检验的预测，就值得用科学方法来验证。</>,
                <><strong>We respect the scientific method.</strong> Even if a theory comes from an unconventional source, as long as it makes testable predictions, it deserves to be evaluated using the scientific method.</>
              )}
            </li>
            <li>
              {t(
                <><strong>我们保持客观。</strong>本站不会使用煽动性语言，不会声称「这一定是真的」，也不会轻率地否定。我们让事实和数据说话。</>,
                <><strong>We remain objective.</strong> This site will not use sensationalist language, will not claim &quot;this must be true,&quot; nor will it rashly dismiss anything. We let facts and data speak for themselves.</>
              )}
            </li>
          </ul>
        </div>

        <h2>{t("免责声明", "Disclaimer")}</h2>
        <div className="bg-yellow-50 border border-yellow-200 p-4 rounded-lg my-6">
          <ul className="text-sm text-yellow-800 space-y-2">
            <li>
              {t(
                "本站呈现的是张祥前的理论体系和实验报告，不代表本站编者认同这些理论的正确性。",
                "This site presents Zhang Xiangqian's theoretical system and experimental reports. This does not imply that the site's editors endorse the correctness of these theories."
              )}
            </li>
            <li>
              {t(
                "实验方案仅供参考。实验涉及电气设备，存在安全风险。实验者需自行评估风险并承担全部责任。",
                "Experimental designs are for reference only. Experiments involve electrical equipment and carry safety risks. Experimenters must assess risks and assume full responsibility themselves."
              )}
            </li>
            <li>
              {t(
                "本站与张祥前本人无利益关系。本站不销售任何产品，不接受捐赠，不提供投资建议。",
                "This site has no financial relationship with Zhang Xiangqian. This site does not sell any products, accept donations, or provide investment advice."
              )}
            </li>
            <li>
              {t(
                "美国海军专利信息来源于美国专利商标局公开文件，本站对专利内容的解读仅供参考。",
                "US Navy patent information is sourced from publicly available documents of the United States Patent and Trademark Office. This site's interpretation of patent content is for reference only."
              )}
            </li>
          </ul>
        </div>

        <h2>{t("联系我们", "Contact Us")}</h2>
        <p>
          {t(
            "如果你是物理学研究者，对复现实验有兴趣，或者发现本站信息有误，欢迎通过以下方式联系：",
            "If you are a physics researcher interested in replicating experiments, or if you find any errors on this site, please contact us through the following channels:"
          )}
        </p>
        <ul>
          <li>{t("电子邮件：（即将开通）", "Email: (coming soon)")}</li>
        </ul>
      </div>

      <NextRead
        locale={loc}
        items={[
          {
            href: "/about/zhang",
            title: t("张祥前简介", "About Zhang Xiangqian"),
            description: t(
              "了解这位坚持四十年的民间物理学家",
              "Learn about this self-taught physicist's 40-year journey"
            ),
          },
          {
            href: "/theory/overview",
            title: t("理论总览", "Theory Overview"),
            description: t(
              "从这里开始了解统一场论",
              "Start here to learn about the unified field theory"
            ),
          },
        ]}
      />
    </div>
  );
}
